### ISSUE TITLE
Unecessary Line of Code

### ISSUE THREAD

**Issue by sible777** [linkeddata/node-webid#12]
Hello,

In the README there seems to be a line of code that is not necessary and doesn't need to be present in the section about [verifying](https://github.com/linkeddata/node-webid/blob/master/README.md#usage) a webid.

``` javascript
var agentWebId = 'https://corysabol.databox.me/profile/card#me'
```

It seems that this may have been copied out from some work in progress code/ test code that I had written since that is my webid.

**Comment by dmitrizagidulin** [comment]
@sible777 Thanks for the catch, will remove that line.

**Comment by dmitrizagidulin** [comment]
@sible777 Thanks for the catch, will remove that line.

**Comment by sible777** [comment]
@dmitrizagidulin No problemo, have a good day :smile:
